# Generated by Django 2.0.4 on 2018-05-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180523_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='ddl_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.LargeDeadline'),
        ),
    ]
