site_name: Timetable
site_description: a awesome timetable for the backend of a wechat app
repo_url: https://github.com/AwesomeTimetable/AwesomeTimetable
site_dir: site
copyright: Copyright &copy; 2018, <a href="https://github.com/AwesomeTimetable">AwesomeTimetable</a>.
dev_addr: 0.0.0.0:8001

pages:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
